### ISSUE TITLE
Why to use template?

### ISSUE THREAD

**Issue by vaibhavsingh97** [freeCodeCampDelhi/freeCodeCampDelhi.github.io#1]
We can build a website from scratch.

**Comment by varunzxzx** [comment]
Yes, We should make a website from scratch

**Comment by vaibhavsingh97** [comment]
So we should delete the existing codebase and start with the new codebase. But before that need to freeze the framework and other plugins. So create a new issue would be fine to discuss.

**Comment by ashwamegh** [comment]
Yeah @vaibhavsingh97 We would be making our website from scratch.. We need a wireframe for that.

**Comment by vaibhavsingh97** [comment]
Can you create milestones as i am not able to or create me, owner of this repo. I can help with development so if you need wireframe we need volunteers

**Comment by vaibhavsingh97** [comment]
Also please remove this template and associated files.

**Comment by ashwamegh** [comment]
@vaibhavsingh97 Please provide your email using the Slack form posted in Fb group..will add u to slack..We have already a bunch of volunteers for the website...We'll be coordinating together..

**Comment by vaibhavsingh97** [comment]
Sure! E: vaibhav.singh.14cse@bml.edu.in
